version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /api
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /frontend
    schedule:
      interval: daily
