name: Orama Package Reindex

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment for deployment"
        type: choice
        options:
          - prod
          - staging
        required: true

permissions:
  contents: read

jobs:
  reindex_orama:
    runs-on: ubuntu-22.04
    environment:
      name: ${{ github.event.inputs.environment }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - uses: denoland/setup-deno@909cc5acb0fdd60627fb858598759246509fa755 # v2.0.2
      - name: Deploy
        env:
          ORAMA_PACKAGE_INDEX_ID: ${{ secrets.ORAMA_PACKAGE_INDEX_ID }}
          ORAMA_PACKAGE_PRIVATE_API_KEY: ${{ secrets.ORAMA_PACKAGE_PRIVATE_API_KEY }}
          JSR_ENDPOINT_URL: ${{ vars.ENVIRONMENT_URL }}
        run: deno task tools:orama:package_reindex
